### ISSUE TITLE
Is it possible to use nginx as proxy

### ISSUE THREAD

**Issue by minozheros** [agmm/standalone-rpi#2]
Hi, first off, thanks for your awesome work. I was wondering if it is possible to use nginx instead of caddy to connect to the syncing server as i have multiple websites that i serve and multiple proxies already. 

Regards Klaus

**Comment by agmm** [comment]
Yes, you could do something similar to what was done with Caddy, or you could expose `api-gateway` to the host machine and then treat it like any other web service.
